### ISSUE TITLE
设备id怎么填，为啥抓电费这么麻烦

### ISSUE THREAD

**Issue by cruocn** [Andtun02/school-charge-open#1]
不能直接
http://h5cloud.17wanxiao.com:8080/CloudPayment/user/getRoomState.do?payProId=953&schoolcode=xxx&businesstype=2&roomverify=xxx吗

**Comment by Andtun02** [comment]
1. tool文件夹有个RegisterDeviceID.exe进行注册
2. 不能（至少我当时不行），你只需要自己请求一下api你就知道，他需要验证token，否则无法获取电费信息

**Comment by Andtun02** [comment]
> 不能直接 [http://h5cloud.17wanxiao.com:8080/CloudPayment/user/getRoomState.do?payProId=953&schoolcode=xxx&businesstype=2&roomverify=xxx吗](http://h5cloud.17wanxiao.com:8080/CloudPayment/user/getRoomState.do?payProId=953&schoolcode=xxx&businesstype=2&roomverify=xxx%E5%90%97)

1. tool文件夹有个RegisterDeviceID.exe进行注册
2. 不能（至少我当时不行），你只需要自己请求一下api你就知道，他需要验证token，否则无法获取电费信息

**Comment by cruocn** [comment]
好的谢谢，我研究了好几天就卡在url原来不能直接请求
